# Generated by Django 5.2.3 on 2025-06-27 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'FHIR Patient Data', 'verbose_name_plural': 'FHIR Patient Data'},
        ),
        migrations.RemoveField(
            model_name='patientresource',
            name='resource_id',
        ),
        migrations.AddField(
            model_name='patientresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 27, 6, 49, 38, 991509, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientresource',
            name='fhir_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
